server:
  port: 9002

spring:
  application:
    name: eureka-server-cluster

eureka:
  instance:
    hostname: eureka-server-02
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-01:9001/eureka/